# Generated by Django 4.2.28 on 2026-03-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('audit_manager', 'Audit Manager'), ('auditee_head', 'Auditee Head'), ('observer', 'Observer')], default='', max_length=30),
        ),
    ]
